name: Test
on:
    push:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: clone repo
              uses: actions/checkout@v3
            - name: install nodejs 18
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: build npm
              run: npm ci
            - name: run test
              run: npm test

